p8105\_hw6\_niz2000
================
Nora Zakaria
11/25/2019

## Load Tidyverse, Modelr, and Class Datasets

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ──────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(p8105.datasets)
library(modelr)
```

# Problem 1

## Load and Tidy the Birthweight Data

``` r
birthweight = 
  read_csv(file = "./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
      babysex = fct_recode(babysex,
                  "male" = "1", "female" = "2"),
    frace = as.factor(frace),
      frace = fct_recode(frace,
                  "white" = "1", "black" = "2", "asian" = "3", 
                  "Puerto Rican" = "4", "Other" = "8", "Unknown" = "9"),
    malform = as.factor(malform),
      malform = fct_recode(malform,
                  "absent" = "0", "present" = "1"),             
    mrace = as.factor(mrace),
      mrace = fct_recode(mrace,
                  "white" = "1", "black" = "2", "asian" = "3", 
                  "Puerto Rican" = "4", "Other" = "8"))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
birthweight
```

    ## # A tibble: 4,342 x 20
    ##    babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##    <fct>   <dbl>   <dbl> <dbl> <dbl>   <dbl> <fct>   <dbl> <fct>      <dbl>
    ##  1 female     34      51  3629   177      35 white    39.9 absent        13
    ##  2 male       34      48  3062   156      65 black    25.9 absent        14
    ##  3 female     36      50  3345   148      85 white    39.9 absent        12
    ##  4 male       34      52  3062   157      55 white    40   absent        14
    ##  5 female     34      52  3374   156       5 white    41.6 absent        13
    ##  6 male       33      52  3374   129      55 white    40.7 absent        12
    ##  7 female     33      46  2523   126      96 black    40.3 absent        14
    ##  8 female     33      49  2778   140       5 white    37.4 absent        12
    ##  9 male       36      52  3515   146      85 white    40.3 absent        11
    ## 10 male       33      50  3459   169      75 black    40.7 absent        12
    ## # … with 4,332 more rows, and 10 more variables: mheight <dbl>,
    ## #   momage <dbl>, mrace <fct>, parity <dbl>, pnumlbw <dbl>, pnumsga <dbl>,
    ## #   ppbmi <dbl>, ppwt <dbl>, smoken <dbl>, wtgain <dbl>

The four categorical variables in the dataset: babysex, frace, malform,
and mrace, were converted from numeric to factor variables. These
factors were also recoded in order for variable codes to be more
descriptive. For example in the babysex variable, the factors now
display “male” and “female,” opposed to 1 and 2. There are 4342
observations and 20 variables in the birthweight dataset.

### Test for Missing Values

After tidying, the missing\_test dataframe was created to detect if
there are any missing values in the dataset.

``` r
missing_test = birthweight %>%
  summarise_all((funs(sum(is.na(.))))) 
missing_test
```

    ## # A tibble: 1 x 20
    ##   babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##     <int> <int>   <int> <int> <int>   <int> <int>   <int>   <int>    <int>
    ## 1       0     0       0     0     0       0     0       0       0        0
    ## # … with 10 more variables: mheight <int>, momage <int>, mrace <int>,
    ## #   parity <int>, pnumlbw <int>, pnumsga <int>, ppbmi <int>, ppwt <int>,
    ## #   smoken <int>, wtgain <int>

As we see in the missing\_test outputted table, there are 0 missing
values in each of the variable columns, indicating that there are no
missing values in the birthweight dataset.

## Regression Model for Birthweight

In this linear regression model for the birthweight (bwt) outcome,
predictors include mother’s pre-pregnancy BMI (ppbmi), mother’s weight
gain during pregnancy in pounds (wtgain), mother’s age at delivery in
years (momage), the number of live births prior to this pregnancy
(parity), and the average number of cigarettes smoked per day during
pregnancy (smoken). These variables were selected based on previous
academic literature findings on the factors that underly birthweight. In
addition to mother’s starting weight, weight gain during preganancy, and
age, birth order and behavioral factors such as smoking all contribute
to the birthweight of a
newborn.

``` r
fit = lm(bwt ~ ppbmi + wtgain + momage + parity + smoken, data = birthweight)
fit
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ ppbmi + wtgain + momage + parity + smoken, 
    ##     data = birthweight)
    ## 
    ## Coefficients:
    ## (Intercept)        ppbmi       wtgain       momage       parity  
    ##     2040.46        18.02        12.94        21.05       -97.50  
    ##      smoken  
    ##       -6.64

``` r
fit_summary_table = fit %>%
  broom::tidy() %>%
  knitr::kable(digits = 3) 
fit_summary_table
```

| term        | estimate | std.error | statistic | p.value |
| :---------- | -------: | --------: | --------: | ------: |
| (Intercept) | 2040.457 |    65.343 |    31.227 |   0.000 |
| ppbmi       |   18.018 |     2.329 |     7.737 |   0.000 |
| wtgain      |   12.938 |     0.678 |    19.084 |   0.000 |
| momage      |   21.053 |     1.915 |    10.992 |   0.000 |
| parity      | \-97.500 |    71.492 |   \-1.364 |   0.173 |
| smoken      |  \-6.640 |     0.995 |   \-6.672 |   0.000 |

The linear model summary table provides the regression coefficients,
standard error, test statistic, and p-value for all predictors in our
model. All p-values were less than 0.05, apart from the “parity”
variable, therefore “parity” is the only predictor in our model that is
not statistically significant. Additionally, our regression coefficients
for “parity” and “smoken” are negative, therefore demonstrating a
negative linear relationship between the predictor and our birthweight
outcome, with the remaining variables demonstrating a positive linear
association.

## Plot of Model Residuals and Fitted Values

``` r
modelr::add_predictions(birthweight, fit)
```

    ## # A tibble: 4,342 x 21
    ##    babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##    <fct>   <dbl>   <dbl> <dbl> <dbl>   <dbl> <fct>   <dbl> <fct>      <dbl>
    ##  1 female     34      51  3629   177      35 white    39.9 absent        13
    ##  2 male       34      48  3062   156      65 black    25.9 absent        14
    ##  3 female     36      50  3345   148      85 white    39.9 absent        12
    ##  4 male       34      52  3062   157      55 white    40   absent        14
    ##  5 female     34      52  3374   156       5 white    41.6 absent        13
    ##  6 male       33      52  3374   129      55 white    40.7 absent        12
    ##  7 female     33      46  2523   126      96 black    40.3 absent        14
    ##  8 female     33      49  2778   140       5 white    37.4 absent        12
    ##  9 male       36      52  3515   146      85 white    40.3 absent        11
    ## 10 male       33      50  3459   169      75 black    40.7 absent        12
    ## # … with 4,332 more rows, and 11 more variables: mheight <dbl>,
    ## #   momage <dbl>, mrace <fct>, parity <dbl>, pnumlbw <dbl>, pnumsga <dbl>,
    ## #   ppbmi <dbl>, ppwt <dbl>, smoken <dbl>, wtgain <dbl>, pred <dbl>

``` r
modelr::add_residuals(birthweight, fit)
```

    ## # A tibble: 4,342 x 21
    ##    babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##    <fct>   <dbl>   <dbl> <dbl> <dbl>   <dbl> <fct>   <dbl> <fct>      <dbl>
    ##  1 female     34      51  3629   177      35 white    39.9 absent        13
    ##  2 male       34      48  3062   156      65 black    25.9 absent        14
    ##  3 female     36      50  3345   148      85 white    39.9 absent        12
    ##  4 male       34      52  3062   157      55 white    40   absent        14
    ##  5 female     34      52  3374   156       5 white    41.6 absent        13
    ##  6 male       33      52  3374   129      55 white    40.7 absent        12
    ##  7 female     33      46  2523   126      96 black    40.3 absent        14
    ##  8 female     33      49  2778   140       5 white    37.4 absent        12
    ##  9 male       36      52  3515   146      85 white    40.3 absent        11
    ## 10 male       33      50  3459   169      75 black    40.7 absent        12
    ## # … with 4,332 more rows, and 11 more variables: mheight <dbl>,
    ## #   momage <dbl>, mrace <fct>, parity <dbl>, pnumlbw <dbl>, pnumsga <dbl>,
    ## #   ppbmi <dbl>, ppwt <dbl>, smoken <dbl>, wtgain <dbl>, resid <dbl>

``` r
birthweight %>%
  modelr::add_residuals(fit) %>%
  modelr::add_predictions(fit) %>%
  ggplot(aes(x = pred, y = resid)) +
    geom_point(aes(color = "viridis"), show.legend = FALSE) +
    labs(
      title = "Model Residuals Against Fitted Values",
      x = "Fitted Values",
      y = "Residuals")  +
    viridis::scale_color_viridis(discrete = TRUE) 
```

![](p8105_hw6_niz2000_files/figure-gfm/Model%20Plot-1.png)<!-- -->

The scatterplot of residuals against fitted values is concentrated
around fitted values from 2800 to 33000, and residual values from -1000
to 1000. ADD DESCRIPTIONS

## Comparing Fit Models

Next, the “fit” model will be compared to two additional models:

  - The “main\_effects\_fit” model, including length at birth and
    gestational age as predictors; and
  - The “interaction\_fit” model, including head circumference, length
    at birth, sex, and all interacting terms as predictors.

### Predictors: Length at Birth and Gestational Age Main Effects

``` r
main_effects_fit = lm(bwt ~ blength + gaweeks, data = birthweight)
main_effects_fit 
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks, data = birthweight)
    ## 
    ## Coefficients:
    ## (Intercept)      blength      gaweeks  
    ##    -4347.67       128.56        27.05

As there are no interaction terms, the length\_age\_fit regression model
outputs an intercept, and two coefficients for each
predictor.

### Predictors: Head Circumference, Length, Sex, and All Interacting Terms

``` r
interaction_fit = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + 
  blength*babysex + bhead*blength*babysex, data = birthweight)
interaction_fit
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ bhead + blength + babysex + bhead * blength + 
    ##     bhead * babysex + blength * babysex + bhead * blength * babysex, 
    ##     data = birthweight)
    ## 
    ## Coefficients:
    ##                 (Intercept)                        bhead  
    ##                  -7176.8170                     181.7956  
    ##                     blength                babysexfemale  
    ##                    102.1269                    6374.8684  
    ##               bhead:blength          bhead:babysexfemale  
    ##                     -0.5536                    -198.3932  
    ##       blength:babysexfemale  bhead:blength:babysexfemale  
    ##                   -123.7729                       3.8781

As there are interaction terms, the interaction\_terms\_fit regression
model outputs an intercept, and seven coefficients, three for each
predictor, three for interaction terms between two predictors, and one
coefficient for the interaction term between all three predictors.

### Comparing Cross-Validated Prediction Errors

In order to compare the “fit,” “main\_effects\_fit,” and
“interaction\_fit” model, cross-validation will be emplored. Cross
validation provides a way to compare the predictive performance of
competing methods.

``` r
cv_df = 
  crossv_mc(birthweight, 100) %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

``` r
cv_df = cv_df %>%
  mutate(
    fit = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    main_effects_fit  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    interaction_fit = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + 
        bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight))) %>%
  mutate(
    rmse_fit = map2_dbl(fit, test, ~rmse(model = .x, data = .y)),
    rmse_main_effects = map2_dbl(main_effects_fit, test, ~rmse(model = .x, data = .y)),
    rmse_interaction = map2_dbl(interaction_fit, test, ~rmse(model = .x, data = .y)))
 
cv_df %>%
  select(starts_with("rmse")) %>%
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rsme_") %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = model, y = rmse, color = model)) +
    geom_violin() +
    labs(
      title = "Cross-Validated Prediction Errors",
      x = "Model",
      y = "RMSE") +
    viridis::scale_color_viridis(discrete = TRUE) 
```

![](p8105_hw6_niz2000_files/figure-gfm/Cross%20Validation-1.png)<!-- -->

Make this comparison in terms of the cross-validated prediction error;
use crossv\_mc and functions in purrr as appropriate. ADD DESCRIPTION.

# Problem 2

## Load 2017 Central Park NOAA Weather Data

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## Registered S3 method overwritten by 'crul':
    ##   method                 from
    ##   as.character.form_file httr

    ## Registered S3 method overwritten by 'hoardr':
    ##   method           from
    ##   print.cache_info httr

    ## file path:          /Users/Michael/Library/Caches/rnoaa/ghcnd/USW00094728.dly

    ## file last updated:  2019-10-31 23:42:54

    ## file min/max dates: 1869-01-01 / 2019-10-31

``` r
weather_df
```

    ## # A tibble: 365 x 6
    ##    name           id          date        prcp  tmax  tmin
    ##    <chr>          <chr>       <date>     <dbl> <dbl> <dbl>
    ##  1 CentralPark_NY USW00094728 2017-01-01     0   8.9   4.4
    ##  2 CentralPark_NY USW00094728 2017-01-02    53   5     2.8
    ##  3 CentralPark_NY USW00094728 2017-01-03   147   6.1   3.9
    ##  4 CentralPark_NY USW00094728 2017-01-04     0  11.1   1.1
    ##  5 CentralPark_NY USW00094728 2017-01-05     0   1.1  -2.7
    ##  6 CentralPark_NY USW00094728 2017-01-06    13   0.6  -3.8
    ##  7 CentralPark_NY USW00094728 2017-01-07    81  -3.2  -6.6
    ##  8 CentralPark_NY USW00094728 2017-01-08     0  -3.8  -8.8
    ##  9 CentralPark_NY USW00094728 2017-01-09     0  -4.9  -9.9
    ## 10 CentralPark_NY USW00094728 2017-01-10     0   7.8  -6  
    ## # … with 355 more rows

There are 365 observations and 6 variables in the NOAA weather dataset
for Central Park. Key variables for subsequent analyses include “tmin”
and “tmax.”

## Central Park Weather Bootstrap Data Frame

``` r
weather_bootstrap = weather_df %>%
  modelr::bootstrap(n = 5000) %>%
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)))
 weather_bootstrap
```

    ## # A tibble: 5,000 x 3
    ##    strap      .id   models
    ##    <list>     <chr> <list>
    ##  1 <resample> 0001  <lm>  
    ##  2 <resample> 0002  <lm>  
    ##  3 <resample> 0003  <lm>  
    ##  4 <resample> 0004  <lm>  
    ##  5 <resample> 0005  <lm>  
    ##  6 <resample> 0006  <lm>  
    ##  7 <resample> 0007  <lm>  
    ##  8 <resample> 0008  <lm>  
    ##  9 <resample> 0009  <lm>  
    ## 10 <resample> 0010  <lm>  
    ## # … with 4,990 more rows

The resulting weather\_bootstrap dataframe consists of 5,000 bootstrap
samples. The underlying simple linear regression model displays “tmax”
as the response, and “tmin” as the predictor of interest.

## Distribution of log(β̂ 0∗β̂ 1)

``` r
logbeta_plot = weather_bootstrap %>%
  mutate(results = map(models, broom::tidy)) %>%
  select(results) %>%
  unnest(results) %>%
  select(term, estimate) %>%
  pivot_wider(
    names_from = "term",
    values_from = "estimate") %>%
  unnest() %>%
  janitor::clean_names() %>%
  mutate(intercept_beta1 = intercept*tmin,
         log_intercept_beta1 = log(intercept_beta1)) %>%
  ggplot(aes(x = log_intercept_beta1)) +
    geom_density() +
    labs(
      title = "Distribution of Beta0*Beta1",
      x = "Log(Beta0*Beta1)",
      y = "Density") +
    viridis::scale_color_viridis(discrete = TRUE) +
    theme(plot.title = element_text(hjust = 0.5))
```

    ## Warning: Values in `estimate` are not uniquely identified; output will contain list-cols.
    ## * Use `values_fn = list(estimate = list)` to suppress this warning.
    ## * Use `values_fn = list(estimate = length)` to identify where the duplicates arise
    ## * Use `values_fn = list(estimate = summary_fun)` to summarise duplicates

    ## Warning: `cols` is now required.
    ## Please use `cols = c(`(Intercept)`, tmin)`

``` r
logbeta_plot
```

![](p8105_hw6_niz2000_files/figure-gfm/Log\(Beta0*Beta1\)%20Plot-1.png)<!-- -->

ADD DESCRIPTION

### 95% CI of log(β̂ 0∗β̂ 1)

``` r
weather_bootstrap %>%
  mutate(results = map(models, broom::tidy)) %>%
  select(results) %>%
  unnest(results) %>%
  select(term, estimate) %>%
  pivot_wider(
    names_from = "term",
    values_from = "estimate") %>%
  unnest() %>%
  janitor::clean_names() %>%
  mutate(intercept_beta1 = intercept*tmin,
    log_intercept_beta1 = log(intercept_beta1)) %>%
  pull(log_intercept_beta1) %>%
  as.vector() %>%
  quantile(probs = c(0.025, 0.975), na.rm = TRUE)
```

    ##     2.5%    97.5% 
    ## 1.965314 2.058781

The 95% confidence interval for the log(β̂ 0∗β̂ 1) is (1.97, 2.06).

## Distribution of r̂ 2

``` r
r_squared_plot = weather_bootstrap %>%
  mutate(results = map(models, broom::glance)) %>%
  select(results) %>%
  unnest(results) %>%
  ggplot(aes(x = r.squared)) +
    geom_density() +
    labs(
      title = "Distribution of R^2",
      x = "R^2",
      y = "Density") +
    viridis::scale_color_viridis(discrete = TRUE) +
    theme(plot.title = element_text(hjust = 0.5))
r_squared_plot
```

![](p8105_hw6_niz2000_files/figure-gfm/R%5E2%20Plot-1.png)<!-- -->

ADD DESCRIPTION

### 95% CI of r̂ 2

``` r
weather_bootstrap %>%
  mutate(
    results = map(models, broom::glance)) %>%
  select(results) %>%
  unnest(results) %>%
  pull(r.squared) %>%
  as.vector() %>%
  quantile(probs = c(0.025, 0.975), na.rm = TRUE)
```

    ##      2.5%     97.5% 
    ## 0.8944866 0.9271505

The 95% confidence interval for the r.squared value is (0.89, 0.93).
