---
title: "p8105_hw6_niz2000"
author: "Nora Zakaria"
date: "11/25/2019"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
```


# Problem 1

## Load and Clean the Children's Birthweight Data
```{r}
#Load and Tidy the Data
birthweight = 
  read_csv(file = "./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
      babysex = fct_recode(babysex,
                  "male" = "1", "female" = "2"),
    frace = as.factor(frace),
      frace = fct_recode(frace,
                  "white" = "1", "black" = "2", "asian" = "3", 
                  "Puerto Rican" = "4", "Other" = "8", "Unknown" = "9"),
    malform = as.factor(malform),
      malform = fct_recode(malform,
               "absent" = "0", "present" = "1"),             
    mrace = as.factor(mrace),
      mrace = fct_recode(mrace,
                  "white" = "1", "black" = "2", "asian" = "3", 
                  "Puerto Rican" = "4", "Other" = "8"))
birthweight
```
The four categorical variables in the dataset, babysex, frace, malform, and mrace, were 
colsums(is.na(birthweight))

# Problem 2

## Load 2017 Central Park NOAA Weather Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


